version: "3.3"

services:
    wechat-box:
        image: "henryxiaoyang/wechat-box-3.9.5.81:latest"
        restart: unless-stopped
        container_name: "wechat-box"
        environment:
            WC_AUTO_RESTART: "yes"
        ports:
            - "8080:8080"
        volumes:
              - "wechat-box-WeChatFiles:/home/app/WeChat Files/"
        tty: true